<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Parte 38</title>
	<link rel="icon" href="../../../../media/book.ico">
	<link rel="stylesheet" href="../../styles.css">
</head>
<body>
	<h1 class="titulo-principal">Control y manejo de errores</h1>
	<h4 class="enlace-volver"><a href="../capitulo9.html">Volver al capitulo</a></h4>
	<hr>

	<!-- Sentencia de bloque -->
	<h3>Sentencia de bloque</h3>
	<p>Las sentencia de bloque se define con {}, y definen un nuevo ambito de variables.</p>
	<!-- codigo -->
	<code>
		let nombre = 'pedro'; <br>
		{ <br> &nbsp&nbsp&nbsp
			let nombre = 'jorge'; <br> &nbsp&nbsp&nbsp
			alert(nombre); <strong>// jorge</strong> <br>
		} <br>
		alert(nombre); <strong>// pedro</strong> <br>
	</code>


	<!-- Errores y sus tipos basicos -->
	<h3>Errores y sus tipos basicos</h3>
	<p>
		Son errores inesperados al ejecutar el programa. Los errores fundamentales que podemos obtener en JavaScript son:
	</p>
	<ul>
		<li>Error</li>
		<li>EvalError</li>
		<li>InternalError</li>
		<li>RangeError</li>
		<li>ReferenceError</li>
		<li>SintaxError</li>
		<li>TypeError</li>
		<li>URIError</li>
	</ul>

	<!-- try { ... } catch(error) { ... } -->
	<h3>try { ... } catch(error) { ... }</h3>
	<p>Cuando usamos try se desactivan los <em>Event Handlers</em> (Manipuladores de eventos) que disparan los errores. En su lugar si hay un error este es pasado como parametro a catch, para asi poder manejarlo nosotros.</p>
	<p>
		Esta sentencia no controla los errores de sintaxis, sino mas bien los errores logicos en el programa que podriamos esperar.
	</p>
	<!-- codigo -->
	<code>
		try { <br> &nbsp&nbsp&nbsp
			variable <br>
		} catch(error) { <br> &nbsp&nbsp&nbsp
			console.log(error); <strong>// ReferenceError: variable is not defined</strong> <br>
			console.log(typeof error); <strong>// Object</strong> <br>
		}
	</code>

	<!-- finally -->
	<h3>finally</h3>
	<p>Esta sentencia define un bloque de codigo que se ejecutara haya, o no haya ocurrido un error.</p>
	<!-- codigo -->
	<code>
		try { <br> &nbsp&nbsp&nbsp
			let variable = 45; <br>
		} catch { <br> &nbsp&nbsp&nbsp
			console.log('Ha ocurrido un error en el primer codigo'); <br>
		} finally { <br> &nbsp&nbsp&nbsp
			console.log('La primera prueba ha finalizado'); <strong>// La primera prueba ha finalizado</strong> <br>
		} <br><br>
		
		try { <br> &nbsp&nbsp&nbsp
			variable  <br>
		} catch { <br> &nbsp&nbsp&nbsp
			console.log('Ha ocurrido un error en el segundo codigo'); <strong>// Ha ocurrido un error en el segundo codigo</strong><br>
		} finally { <br>&nbsp&nbsp&nbsp
			console.log('La segunda prueba ha finalizado'); <strong>// La segunda prueba ha finalizado</strong><br>
		}
	</code>

	<!-- throw -->
	<h3>throw</h3>
	<p>Esta sentencia lanza lo que sea que le pasemos como un error.</p>
	<!-- codigo -->
	<code>
		try { <br> &nbsp&nbsp&nbsp
			throw 'Guitarra, soledad y un planeta azul'; <br>
		} catch (error) { <br> &nbsp&nbsp&nbsp
			console.log(error); <strong>// Guitarra, soledad y un planeta azul</strong> <br>
		}
	</code>

	<!-- <script src="programa.js"></script> -->
</body>
</html>